### PR TITLE
fix document updates including supporting room avatars

### PR DESCRIPTION
**Pull request by debdutdeb**

### CODE REVIEW

**Comment by wanderlage** [comment]
I did a test using this PR, and it apparently resolved the issue https://github.com/RocketChat/filestore-migrator/issues/18, but ended up creating a new one.
It is not respecting the value of the Store variable.

**Comment by debdutdeb** [comment]
I ran a test too and it failed, or rather didn't migrate right. Didn't figure out why. Thanks for the info. I'm gonna check

**Comment by kassemz** [comment]
Hi @debdutdeb any update on this issue?

I think I'm getting the same error when doing migration from file system to S3:

I'm not doing anything with GoogleStorage but it is showing up in the error.

````
2023/12/09 20:46:20 Connecting to database to detect source upload config
2023/12/09 20:46:20 Source set as: FileSystem
2023/12/09 20:46:20 Destination set as: AmazonS3
2023/12/09 20:46:20 [12/09/2023 20:46:20] Source store type set to:  FileSystem
2023/12/09 20:46:20 [12/09/2023 20:46:20] Destination store type set to:  AmazonS3
2023/12/09 20:46:20 Beginning migration of files
2023/12/09 20:46:20 [12/09/2023 20:46:20] Store:  Uploads
2023/12/09 20:46:20 [12/09/2023 20:46:20] uniqueId {uniqueID 8b4fb083-hjkk-99aa-87c3-28acfab6c5f8}
2023/12/09 20:46:20 [12/09/2023 20:46:20] rocketchat_uploads FileSystem:Uploads
2023/12/09 20:46:21 [12/09/2023 20:46:21] Found 149562 files

2023/12/09 20:46:21 [12/09/2023 20:46:21] [1/149562] Downloading Clipboard - July 19, 2018 6:44 PM from: FileSystem

2023/12/09 20:46:21 [12/09/2023 20:46:21] [1/149562] Uploading to AmazonS3 to: 8b4fb083-hjkk-99aa-87c3-28acfab6c5f8/uploads/GENERAL/JWdHh4cwpAH6Fn2AY/xYri2RTGWhwBQMK7m

panic: write exception: write errors: [Updating the path 'GoogleStorage' would create a conflict at 'GoogleStorage']

goroutine 1 [running]:
main.main()
        /home/filestore-migrator/cmd/filestore-migrator/main.go:64 +0x8b0
````

**Comment by wanderlage** [comment]
> Hi @debdutdeb any update on this issue?
> 
> I think I'm getting the same error when doing migration from file system to S3:
> 
> I'm not doing anything with GoogleStorage but it is showing up in the error.
> 
> ```
> 2023/12/09 20:46:20 Connecting to database to detect source upload config
> 2023/12/09 20:46:20 Source set as: FileSystem
> 2023/12/09 20:46:20 Destination set as: AmazonS3
> 2023/12/09 20:46:20 [12/09/2023 20:46:20] Source store type set to:  FileSystem
> 2023/12/09 20:46:20 [12/09/2023 20:46:20] Destination store type set to:  AmazonS3
> 2023/12/09 20:46:20 Beginning migration of files
> 2023/12/09 20:46:20 [12/09/2023 20:46:20] Store:  Uploads
> 2023/12/09 20:46:20 [12/09/2023 20:46:20] uniqueId {uniqueID 8b4fb083-hjkk-99aa-87c3-28acfab6c5f8}
> 2023/12/09 20:46:20 [12/09/2023 20:46:20] rocketchat_uploads FileSystem:Uploads
> 2023/12/09 20:46:21 [12/09/2023 20:46:21] Found 149562 files
> 
> 2023/12/09 20:46:21 [12/09/2023 20:46:21] [1/149562] Downloading Clipboard - July 19, 2018 6:44 PM from: FileSystem
> 
> 2023/12/09 20:46:21 [12/09/2023 20:46:21] [1/149562] Uploading to AmazonS3 to: 8b4fb083-hjkk-99aa-87c3-28acfab6c5f8/uploads/GENERAL/JWdHh4cwpAH6Fn2AY/xYri2RTGWhwBQMK7m
> 
> panic: write exception: write errors: [Updating the path 'GoogleStorage' would create a conflict at 'GoogleStorage']
> 
> goroutine 1 [running]:
> main.main()
>         /home/filestore-migrator/cmd/filestore-migrator/main.go:64 +0x8b0
> ```
> 
> @wanderlage you did any workarounds?

Yes, i used the code the migrate branch https://github.com/RocketChat/filestore-migrator/tree/migrate
But it only migrates the uploads, and leaves the attachments.

**Comment by debdutdeb** [comment]
@wanderlage wdym by "leaves the attachments"?

**Pull request merged**
